/*
 * generated by Xtext 2.25.0
 */
package io.github.lorenzobettini.tychopomlesstestlanguage;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TychopomlesstestlanguageRuntimeModule extends AbstractTychopomlesstestlanguageRuntimeModule {
}
