/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychotestlanguage.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(TychotestlanguageInjectorProvider)
class TychotestlanguageCompilerTest {
	@Inject extension CompilationTestHelper

	@Test
	def void compileModel() {
		'''
			Hello Xtext!
			Hello World!
		'''.compile [
			Assertions.assertEquals(
				"People to greet: Xtext, World",
				getSingleGeneratedCode
			)
		]
	}
}
