/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychoxbasetestlanguage.tests

import com.google.inject.Inject
import io.github.lorenzobettini.tychoxbasetestlanguage.tychoxbasetestlanguage.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

/**
 * We leave also the Xtend test to make sure that we can still
 * compile Xtend code even with JDK 14
 */
@RunWith(XtextRunner)
@InjectWith(TychoxbasetestlanguageInjectorProvider)
class TychoxbasetestlanguageParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext {
				val String s = "Hello"
				println(s)
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
