language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
      services:
      - xvfb
      env: ADDITIONAL=""
    - os: osx
      osx_image: xcode10.1
      jdk: openjdk11
      env: ADDITIONAL=""

cache:
  directories:
    - '$HOME/.m2'

install: true

before_install:
 - echo $JAVA_HOME

script:
 - mvn -f xtext-tycho-parent/io.github.lorenzobettini.xtextutils.xtext-tycho-parent/pom.xml clean install
 - mvn -U -f testlanguages/tychotestlanguage/io.github.lorenzobettini.tychotestlanguage.parent/pom.xml clean verify $ADDITIONAL

# removes our installed artifacts before storing the cache
before_cache:
 - find $HOME/.m2/repository -name "*lorenzobettini*" -exec rm -rf {} \+

