language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
      services:
      - xvfb
      env: ADDITIONAL=""
    - os: osx
      osx_image: xcode10.1
      jdk: openjdk11
      env: ADDITIONAL=""

cache:
  directories:
    - '$HOME/.m2'

install: true

before_install:
 - echo $JAVA_HOME

script:
# install our POMs
 - mvn -f releng/io.github.lorenzobettini.xtextutils.releng/pom.xml clean install
# run testlanguages using our POMs
 - mvn -U -f testlanguages/tychotestlanguage/io.github.lorenzobettini.tychotestlanguage.parent/pom.xml clean verify $ADDITIONAL
# run it again without source code generation (MWE2 and Xtend are skipped)
 - mvn -f testlanguages/tychotestlanguage/io.github.lorenzobettini.tychotestlanguage.parent/pom.xml clean verify -DskipMWE2 -DskipXtend $ADDITIONAL
# run the pure Maven test project
 - mvn -f testlanguages/maventestlanguage/io.github.lorenzobettini.maventestlanguage.parent/pom.xml clean verify

# removes our installed artifacts before storing the cache
before_cache:
 - find $HOME/.m2/repository -name "*lorenzobettini*" -exec rm -rf {} \+

