/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychoxbasetestlanguage;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TychoxbasetestlanguageStandaloneSetup extends TychoxbasetestlanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new TychoxbasetestlanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
