/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychotestlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TychotestlanguageUiModule extends AbstractTychotestlanguageUiModule {

	public TychotestlanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
