/*
 * generated by Xtext 2.25.0
 */
package io.github.lorenzobettini.tychopomlesstestlanguage.ide;


/**
 * Use this class to register ide components.
 */
public class TychopomlesstestlanguageIdeModule extends AbstractTychopomlesstestlanguageIdeModule {
}
