/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychotestlanguage.ide;


/**
 * Use this class to register ide components.
 */
public class TychotestlanguageIdeModule extends AbstractTychotestlanguageIdeModule {
}
