/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychotestlanguage.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class TychotestlanguageWebModule extends AbstractTychotestlanguageWebModule {
}
