/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychotestlanguage.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.github.lorenzobettini.tychotestlanguage.TychotestlanguageRuntimeModule;
import io.github.lorenzobettini.tychotestlanguage.TychotestlanguageStandaloneSetup;
import io.github.lorenzobettini.tychotestlanguage.ide.TychotestlanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class TychotestlanguageWebSetup extends TychotestlanguageStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TychotestlanguageRuntimeModule(), new TychotestlanguageIdeModule(), new TychotestlanguageWebModule()));
	}
	
}
