/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychoxbasetestlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TychoxbasetestlanguageUiModule extends AbstractTychoxbasetestlanguageUiModule {

	public TychoxbasetestlanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
