/*
 * generated by Xtext 2.25.0
 */
package io.github.lorenzobettini.maventestlanguage.ide


/**
 * Use this class to register ide components.
 */
class MaventestlanguageIdeModule extends AbstractMaventestlanguageIdeModule {
}
