/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.maventestlanguage.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.github.lorenzobettini.maventestlanguage.MaventestlanguageRuntimeModule;
import io.github.lorenzobettini.maventestlanguage.MaventestlanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MaventestlanguageIdeSetup extends MaventestlanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MaventestlanguageRuntimeModule(), new MaventestlanguageIdeModule()));
	}
	
}
