/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.maventestlanguage.ide;


/**
 * Use this class to register ide components.
 */
public class MaventestlanguageIdeModule extends AbstractMaventestlanguageIdeModule {
}
