/*
 * generated by Xtext 2.25.0
 */
package io.github.lorenzobettini.tychopomlesstestlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TychopomlesstestlanguageUiModule extends AbstractTychopomlesstestlanguageUiModule {

	public TychopomlesstestlanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
