/*
 * generated by Xtext 2.25.0
 */
package io.github.lorenzobettini.tychopomlesstestlanguage.tests

import com.google.inject.Inject
import io.github.lorenzobettini.tychopomlesstestlanguage.tychopomlesstestlanguage.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(TychopomlesstestlanguageInjectorProvider)
class TychopomlesstestlanguageParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
