/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychotestlanguage;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TychotestlanguageStandaloneSetup extends TychotestlanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new TychotestlanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
