/*
 * generated by Xtext 2.20.0
 */
package io.github.lorenzobettini.tychoxbasetestlanguage.ide;


/**
 * Use this class to register ide components.
 */
public class TychoxbasetestlanguageIdeModule extends AbstractTychoxbasetestlanguageIdeModule {
}
