# This workflow will build deploy the Maven artifacts to Maven Central

name: Deploy Maven

on:
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.1
      with:
        java-version: 21
        distribution: temurin
        server-id: central # Value of the Maven central repository
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          !**/*edelta*
        key: ${{ runner.os }}-maven-deploy-${{ hashFiles('**/*.target', '**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-deploy-
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.5
    - name: Remove SNAPSHOT
      run: ./removeSnapshots.sh
    - name: Publish to Apache Maven Central
      run: >
        mvn -f releng/io.github.lorenzobettini.xtextutils.releng/pom.xml
        -Psonatype-oss-release
        clean package deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
